package hr.lcabraja.webshop.repository;

import hr.lcabraja.webshop.model.Product;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class ProductRepository {
    private static ProductRepository singleton = null;
    private List<Product> products = new ArrayList<>();

    private ProductRepository() {
        // Bread
        products.add(new Product(1L, "Alpine", "Ingredients: wheat flour type 850, water, rye flour type 1250, yeast, salt, pregelatinized wheat flour type 1600, barley malt, baked wheat malt flour, enzymes", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/ALPSKI.jpg"));
        products.add(new Product(2L, "Baguette rustique", "Ingredients: wheat flour type 550, water, wheat flour type 850 , milk, salt, yeast, sugar, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/baguette_rustique.jpg"));
        products.add(new Product(3L, "White Dubravica bread", "Ingredients: wheat flour type 550, water, milk, yeast, salt, lard, additives ", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/300X275bijeli_dubravica.jpg"));
        products.add(new Product(4L, "White morning bread", "Ingredients: wheat flour type 550, water, yeast, salt, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/SENDVIC BIJELI 1308.jpg"));
        products.add(new Product(5L, "Morning pumpkin bread", "Ingredients: wheat flour type 850, water, wheat flour type 550, yeast, pumpkin seeds, sunflower seeds, sesame, corn grits, flax seeds, oat grains, soy bran, salt, whey powder, corn white flour, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/BUNDEVIN JUTARNJI 1553.jpg"));
        products.add(new Product(6L, "Bread made under a baking lid", "Ingredients: wheat flour type 850, water, thermally processed corn grits, whole grain wheat flour, wheat flour type 550, corn bran, corn gluten, soy flour, whole grain rye grits, yeast, salt, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/PEKA1169.jpg"));
        products.add(new Product(7L, "Corn baguette", "Ingredients: wheat flour type 550, water, thermally processed corn grits, vegetable oil, yeast, salt, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/KUKURUZNI BAGUETTE 1098.jpg"));
        products.add(new Product(8L, "Corn delicacy", "Ingredients: wheat flour type 850, corn grits, water, yeast, salt, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/KUKURUZNI DELIKATES 1203.jpg"));
        products.add(new Product(9L, "Morning corn bread", "Ingredients: wheat flour type 550, corn flour, thermally processed corn grits, sweet corn, milk, salt, lard, yeast, enzymes", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/300X275kukuruzni_jutarnji 2.jpg"));
        products.add(new Product(10L, "Mixed corn bread", "Ingredients: wheat flour types 550 and 850, water, corn flour, yeast, salt, wheat gluten, partially hydrogenated vegetable fat, sugar, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/KUKURUZNI MJES¦îANI 1196.jpg"));
        products.add(new Product(11L, "Hunter's bread", "Ingredients: wheat flour type 850, water, whole grain rye grits, wheat flour type 550, barley malt, sunflower seeds, pre-gelatinized rye flour, millet flour, oat flakes, flax seeds, crushed soy seeds, wheat bran, roasted wheat malt flour, salt, yeast, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/LOVACKI 1293.jpg"));
        products.add(new Product(12L, "Hunter's loaf", "Ingredients: wheat flour type 850, water, rye grits, salt, yeast, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/LUGARSKA STRUCA 1300.jpg"));
        products.add(new Product(13L, "Whole grain delicacy bread", "Ingredients: rye grits, water, rye flour type 1250, wheat flour type 1100, sunflower seeds, wheat flour type 550, salt, yeast, sugar, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/300X275punozrnati_delikates.jpg"));
        products.add(new Product(14L, "Mixed rye bread", "Ingredients: wheat flour type 850, water, rye flour type 1250, yeast, salt, enzymes, pregelatinized wheat flour type 1600, barley malt, baked wheat malt flour", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/RAZENI MIJESANI 1117.jpg"));
        products.add(new Product(15L, "Country corn bread", "Ingredients: corn flour, wheat flour type 550, water, yeast, salt, oil, lard, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/SELJACKI KUKURUZNI 1265.jpg"));
        products.add(new Product(16L, "White sandwich", "Ingredients: wheat flour type 550 (63%), water, yeast, salt, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/SENDVIC BIJELI 1308.jpg"));
        products.add(new Product(17L, "Half white sandwich", "Ingredients: wheat flour type 850, water, yeast, salt, additives", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/SENDVIC POLUBIJELI 1176.jpg"));
        products.add(new Product(18L, "Zagorski delicacy bread", "Ingredients: wheat flour type 850, water, corn white flour, milk, sunflower oil, yeast, salt, lard, butter ", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/zagorski_del_mali.jpg"));
        products.add(new Product(19L, "Oat bread", "Ingredients: wheat flour type 850, water, whole grain oat grits, hulled sliced oats, oat flakes, rye flour type 1250, yeast, salt, sugar, barley malt, enzymes", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/300X275zobeni_kruh.jpg"));
        products.add(new Product(20L, "Buckwheat bread with walnuts", "Ingredients: wheat flour type 550, water, buckwheat flour, walnuts, butter, sunflower oil, yeast, salt, sugar, enzymes", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/300X275heljdin_kruh_sa_orasima.jpg"));
        products.add(new Product(21L, "Small white Dubravica bread", "Ingredients: wheat flour type 550, water, milk, yeast, salt, lard, additives ", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/300X275bijeli_dubravica.jpg"));
        products.add(new Product(22L, "Bread with olives", "Ingredients: wheat flour type 550, water, Kalamata olives, olive oil, salt, yeast, wheat gluten, enzimes", 3.5, CategoryRepository.getAllCategories().get(0), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Kruh/Pogaca_sa_maslinama_mala.jpg"));
        // Pastry
        products.add(new Product(23L, "Crescent roll with seeds", "Ingredients: wheat flour type 550, milk, sesame seeds, crushed soy seeds, wheat flour type 850, flax seeds, rye flour type 850, whole grain rye grits, sunflower oil, sour cream, sugar, yeast, salt, soy flour, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/KIFLEKI ZRNATI 0958.jpg"));
        products.add(new Product(24L, "Flower roll", "Ingredients: wheat flour type 550, water, yeast, sugar, sunflower oil, salt, margarine, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/CVJETNO PECIVO 0941.jpg"));
        products.add(new Product(25L, "Dubravica hot-dog", "Ingredients: hot-dog, wheat flour type 550, water, thermally processed corn grits, milk, yeast, sunflower oil, salt, mustard, mozzarella cheese, sugar, margarine, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/Hrenovka_Dub.bmp"));
        products.add(new Product(26L, "Corn crescent roll", "Ingredients: wheat flour type 550, milk, pre-gelatinized corn grits, sunflower oil, sour cream, margarine, sugar, yeast, salt, caraway seeds, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/KIFLEKI KUKURUZNI  _0960.jpg"));
        products.add(new Product(27L, "Poppy roll", "Ingredients: wheat flour type 550, water, sunflower oil, powdered milk, sugar, yeast, salt, egg yolk, poppy seeds, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/KLIPIC MAK 2 1057.jpg"));
        products.add(new Product(28L, "Cheese roll", "Ingredients: wheat flour type 550, water, sunflower oil, powdered milk, sugar, yeast, salt, egg yolk, semi-soft cheese, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/KLIPIC SIR 1542.jpg"));
        products.add(new Product(29L, "Corn roll with meat bacon", "Ingredients: wheat flour type 550, milk, pre-gelatinized corn grits, sour cream, sunflower oil, sugar, egg yolk, yeast, meat bacon, salt, olive oil, garlic, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/kuk__panceta_klipic.jpg"));
        products.add(new Product(20L, "Corn roll with bacon", "Ingredients: wheat flour type 550, corn flour, water, bacon, milk, margarine, sugar, salt, yeast, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/spek_r.jpg"));
        products.add(new Product(21L, "Milk crescent roll", "Ingredients: wheat flour type 550, water, sugar, powdered milk 4,5%, margarine, eggs, butter, yeast, salt, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/MLIJECNA KIFLA 0977.jpg"));
        products.add(new Product(22L, "Butter roll", "Ingredients: wheat flour type 550, water, sugar, butter, eggs, yeast, salt, flavour, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/PUTAR STANGICA 1053.jpg"));
        products.add(new Product(23L, "Salt roll", "Ingredients: wheat flour type 550, water, sunflower oil, powdered milk, sugar, yeast, salt, egg yolk, thermostable salt, caraway, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/KLIPIC SLANI 0985.jpg"));
        products.add(new Product(24L, "Oat roll", "Ingredients: wheat flower type 550, water, whole grain oat flour, rye grits, salt, yeast, butter, sugar, rye flour type 1250, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/Zobena_stan.bmp"));
        products.add(new Product(25L, "Roll with seeds", "Ingredients: wheat flour type 550, water, whole grain oat flour, flax and sunflower seeds, rye grits, salt, yeast, butter, sugar, oat grits, sesame seeds, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/zrnata_sta.jpg"));
        products.add(new Product(26L, "Hambi", "Ingredients: wheat flour type 550, water, butter, sugar, yeast, powdered milk, sesame, eggs, additives ", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/HAMBI_mala.jpg"));
        products.add(new Product(27L, "Sandwich roll", "Ingredients: wheat flour type 550, water, butter, sugar, yeast, powdered milk, eggs, additives ", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/SENDVIC PECIVO mala.jpg"));
        products.add(new Product(28L, "Rounded spelt roll", "Ingredients: spelt flour, butter, milk, wheat flour type 550, fresh cheese, zucchini, sunflower oil, egg yolk, yeast, salt, sugar, sesame, eggs, additives", 3.5, CategoryRepository.getAllCategories().get(1), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Peciva/Pirov_puž_sa_tikvicama_mala.jpg"));
        // Fine pastry and sweet rolls
        products.add(new Product(29L, "Croissant", "Ingredients: Ingredients: wheat flour type 550, water, butter, sugar, yeast, egg yolk, salt, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/CROISSANT 1061.jpg"));
        products.add(new Product(30L, "Apricot croissant", "Ingredients: wheat flour type 550, water, butter, apricot jam, sugar, yeast, egg yolk, salt, thermostable sugar, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/croissant_mare.jpg"));
        products.add(new Product(31L, "Chocolate croissant", "Ingredients: wheat flour type 550, water, butter, chocolate filling, sugar, yeast, egg yolk, salt, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/croissant_cok.jpg"));
        products.add(new Product(32L, "Ham and cheese croissant", "Ingredients: wheat flour type 550, water, ham, semi-soft cheese, margarine, yeast, powdered milk, salt, sugar", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/CROISSANT SIR SUNKA 1067.jpg"));
        products.add(new Product(33L, "Jam doughnut", "Ingredients: wheat flour type 550, water, eggs, sugar, butter, sunflower oil, yeast, rum, salt, palm oil, flavour, apricot jam, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/KRAFNA MARMELADA 1041.jpg"));
        products.add(new Product(34L, "Chocolate doughnut", "Ingredients: wheat flour type 550, chocolate filling, chocolate icing, water, eggs, sugar, butter, sunflower oil, yeast, rum, salt, palm oil, flavours, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/krafna.jpg"));
        products.add(new Product(35L, "Corn puff pastry with cheese", "Ingredients: wheat flour type 500, water, cottage cheese, pre-gelatinized corn grits, margarine, yeast, eggs, salt", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/KUKURUZNI SAVITAK SA SIROM 1002.jpg"));
        products.add(new Product(36L, "Crepe with chocolate", "Ingredients: chocolate and hazelnut filling, wheat flour type 550, milk, carbonated water, eggs, sunflower oil, sugar, whipped cream, sour cream 20% MF, chocolate, salt", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/palacinka_s_coko.png"));
        products.add(new Product(37L, "Crepe with walnuts", "Ingredients: walnuts, sour cream 20% M.F., wheat flour type 550, milk, carbonated water, eggs, sunflower oil, sugar, salt, vanilla sugar", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/PALACINKE S ORASIMA  1420.jpg"));
        products.add(new Product(38L, "Crepe with cheese", "Ingredients: cottage cheese, sour cream 20% M.F., wheat flour type 550, milk, carbonated water, eggs, sunflower oil, sugar, salt, lemon juice, vanilla sugar", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/PALAINKE SA SIROM 1419.jpg"));
        products.add(new Product(39L, "Pizzeta", "Ingredients: wheat flour type 550, water, pizza ham, semi-soft cheese, tomato sauce, sunflower oil, margarine, yeast, salt, sugar, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/PIZZETTA 1021.jpg"));
        products.add(new Product(40L, "Bannock with cracklings", "Ingredients: wheat flour type 550, water, cracklings, margarine, sugar, yeast, salt, eggs, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/POGACICA SA CVARCIMA 0998.jpg"));
        products.add(new Product(41L, "Homemade cheese strudel", "Ingredients: wheat flour type 550, water, cottage cheese, eggs, salt, sunflower oil, margarine", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/ZAGORSKI STRUKLI 1032.jpg"));
        products.add(new Product(42L, "Crescent roll with ham", "Ingredients: wheat flour type 550, water, corn grits, butter, ham, cottage cheese, eggs, sesame, margarine, yeast, salt, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/kuruzna_kif_sunka.bmp"));
        products.add(new Product(43L, "Wholegrain blueberry-vanilla puff pastry", "Ingredients: wheat flour 550, vanilla filling, blueberry filling, water, wholegrain wheat flour, butter, sugar, yolk, salt, almonds, glaze, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/Integralna_stan.jpg"));
        products.add(new Product(44L, "Pizza stick", "Ingredients: wheat flour type 550, water, pre-gelatinized corn grits, butter, pizza sauce, cheese, sesame,  additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/Pizza_prutic.jpg"));
        products.add(new Product(45L, "Apple strudel", "Ingredients: apples, wheat flour type 550, sugar, sunflower oil, butter, bread crumbs, thermostable sugar, salt, eggs, cinnamon, aromas, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/mala_strudla_jabuka.jpg"));
        products.add(new Product(46L, "Sour cherry strudel", "Ingredients: sour cherries, wheat flour type 550, water, sugar, sunflower oil, butter, bread crumbs, termostable sugar, salt, eggs", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/STRUDLA_VISNJA_mala.jpg"));
        products.add(new Product(47L, "Pain au chocolat", "Ingredients: wheat flour type 550, butter, water, chocolate, milk chocolate, sugar, cacao powder, eggs, yeast, egg yolk, salt, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/PAIN AU CHOCOLAT_mala.jpg"));
        products.add(new Product(48L, "Gourmet Sausage", "Ingredients: wheat roll, sausage, cheese, mustard, onions, aceto balsamico, sugar, sunflower oil, salt, roasted peppers, pickled peppers, zucchini, vinegar, garlic, spices, additives", 3.5, CategoryRepository.getAllCategories().get(2),"https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Fino pecivo i slastice/Gurmanska_kobasica_300x275.jpg"));
        // Burek
        products.add(new Product(49L, "Burek with meat", "Ingredients: wheat flour type 550, water, beef, pork, onion, margarine, sunflower oil, salt, Vegeta, lard, pepper", 3.5, CategoryRepository.getAllCategories().get(3), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Bureci/BUREK S MESOM 1536.jpg"));
        products.add(new Product(40L, "Burek with cheese", "Ingredients: cottage cheese, wheat flour type 550, water, eggs, margarine, lard, sunflower oil, salt", 3.5, CategoryRepository.getAllCategories().get(3), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Bureci/BUREK SA SIROM1079.jpg"));
        products.add(new Product(51L, "Mini burek with chicken and button mushrooms", "Ingredients: wheat flour type 550, chicken, water, sunflower oil, button mushrooms, sour cream 20% M.F., onion, salt, butter, spices, additives", 3.5, CategoryRepository.getAllCategories().get(3), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Bureci/mini_burek_s_piletinom_i_sampi.jpg"));
        products.add(new Product(52L, "Mini burek with potatoes", "Ingredients: potatoes, wheat flour type 550, sunflower oil, water, onions, butter, Vegeta, salt, pepper, additives", 3.5, CategoryRepository.getAllCategories().get(3), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Bureci/MINI BUREK S KRUMPIROM1069.jpg"));
        products.add(new Product(53L, "Mini burek with meat", "Ingredients: wheat flour type 550, water, sunflower oil, beef, pork, onions, butter, salt, Vegeta, pepper, additives", 3.5, CategoryRepository.getAllCategories().get(3), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Bureci/MINI BUREK S MESOM 1073.jpg"));
        products.add(new Product(54L, "Mini burek with cheese", "Ingredients: fresh cheese, wheat flour type 550, sunflower oil, water, eggs, salt, butter, additives ", 3.5, CategoryRepository.getAllCategories().get(3), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Bureci/MINI BUREK SA SIROM 1076.jpg"));
        // Sandwiches
        products.add(new Product(55L, "Pršut roll", "Ingredients: roll, pršut, butter", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/Klipic_s_prsutom.jpg"));
        products.add(new Product(56L, "Turkey meat sandwich", "Ingredients: seed roll, turkey ham, semi-soft cheese, lettuce, tomato, cucumber, (boiled egg), cream cheese for sandwiches, chives", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/SENDVIC PURETINA_1796 A.jpg"));
        products.add(new Product(57L, "Ham and cheese sandwich", "Ingredients: mini baguette, sandwich ham, semi-soft cheese, lettuce, tomato, cucumber, cream cheese for sandwiches, chives", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/SENDVIC SUNKA SIR _1800 A.jpg"));
        products.add(new Product(58L, "Tuna sandwich", "Ingredients: corn ciabattina, tuna, lettuce, tomato, (boiled egg), cucumber, cream cheese for sandwiches", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/SENDVIC TUNA 1571 A.jpg"));
        products.add(new Product(59L, "Sausage hot sandwich", "Ingredients: ciabattina, debrecinka sausage, semi-soft cheese, mustard, chili powder", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/TOPLI SENDVIC KOBASICA _1604 A.jpg"));
        products.add(new Product(60L, "Tomato-zucchini hot sandwich", "Ingredients: corn ciabattina, tomato, zucchini, semi-soft cheese, tomato sauce, balsamic vinegar, salt, oregano", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/TOPLI SENDVIC MOZZARELLA RAJCICA _1601 A.jpg"));
        products.add(new Product(61L, "Bacon-cream hot sandwich", "Ingredients: corn ciabattina, bacon, sour cream 20% M.F., onion", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/TOPLISENDVIC SPEK VRHNJE _1609 A.jpg"));
        products.add(new Product(62L, "Premium toast roll with ham", "Ingredients: toast roll, smoked ham, tomato, mozzarella cheese, butter, horseradish sauce, pesto genovese", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/SENDVIC PREMIUM TOAST SUNKA_1801 A.jpg"));
        products.add(new Product(63L, "Roll with homemade salami", "Ingredients: roll, homemade salami, butter", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/Klipic_s_domacom_salamom.jpg"));
        products.add(new Product(64L, "Pag roll", "Ingredients: roll, Dalmatinac cheese, butter, tomato pesto, arugula", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/paski_klipic.jpg"));
        products.add(new Product(65L, "Grilled vegetables sandwich", "Ingredients: sandwich roll, grilled vegetables, tomato sauce, green salad, cheese in brine, butter", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/SENDVIC GRIL POVRCE 1583 A.jpg"));
        products.add(new Product(66L, "Roast beef sandwich", "Ingredients: rolls, roast beef, Brie cheese spread, tomato, arugula, walnut, aceto balsamico, horse radish", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/Roast_beef_300x275.jpg"));
        products.add(new Product(67L, "Pršut and truffles sandwich", "Ingredients: corn ciabattina, pršut, tomatoes, mozzarella, truffle spread, butter, arugula, olive pesto", 3.5, CategoryRepository.getAllCategories().get(4), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Sendvici/sendvic_prsut_tartufi_300x275.jpg"));
        // Pizzas
        products.add(new Product(68L, "Pizza Dubravica", "Ingredients: pizza dough, cheese, Tyrolean salami, bacon, tomato sauce, sour cream, olive, oregano", 3.5, CategoryRepository.getAllCategories().get(5), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pizze/PIZZA DUBRAVICA_1782.jpg"));
        products.add(new Product(69L, "Mixed pizza", "Ingredients: pizza dough, cheese, pizza ham, button mushrooms, tomato sauce, olives, oregano", 3.5, CategoryRepository.getAllCategories().get(5), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pizze/PIZZA MIJESANA _1642.jpg"));
        products.add(new Product(70L, "Pizza picante", "Ingredients: pizza dough, cheese, pizza ham, kulen, fresh paprika, tomato sauce, chili peppers, olives, oregano ", 3.5, CategoryRepository.getAllCategories().get(5), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pizze/PIZZA PIKANTE _1646.jpg"));
        products.add(new Product(71L, "Cheese pizza", "Ingredients: pizza dough, cheese, tomato sauce, olives, oregano", 3.5, CategoryRepository.getAllCategories().get(5), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pizze/PIZZA SIR _1628 A.jpg"));
        products.add(new Product(72L, "Ham and cheese pizza", "Ingredients: pizza dough, cheese, pizza ham, tomato sauce, olives, oregano", 3.5, CategoryRepository.getAllCategories().get(5), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pizze/PIZZA SUNKA SIR _1637.jpg"));
        // Salads and yogurts
        products.add(new Product(73L, "Grilled turkey salad", "Ingredients: bulgur, grilled  vegetables (bell pepper, zucchini, eggplant, cherry tomato), turkey, arugula, sunflower oil, spices ", 3.5, CategoryRepository.getAllCategories().get(6), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Salate/SALATA PURETINA GRILL A.jpg"));
        products.add(new Product(74L, "Buckwheat and feta salad", "Ingredients: buckwheat, bell pepper, chickpeas, feta cheese, lettuce, carrot, celery, salt", 3.5, CategoryRepository.getAllCategories().get(6), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pizze/PIZZA DUBRAVICA_1782.jpg"));
        products.add(new Product(75L, "Chicken salad", "Ingredients: fresh salad (iceberg, radicchio, arugula), chicken, cherry tomato, smoked cheese, aceto balsamico, pumpkin seeds ", 3.5, CategoryRepository.getAllCategories().get(6), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pizze/PIZZA MIJESANA _1642.jpg"));
        products.add(new Product(76L, "Tuna salad", "Ingredients: couscous, green salad, tuna, artichokes, peppers, zucchini, cherry tomatoes, kalamata olives, kapari, extravirgin olive oil, vinegar, spices", 3.5, CategoryRepository.getAllCategories().get(6), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pizze/PIZZA PIKANTE _1646.jpg"));
        products.add(new Product(77L, "Yogurt musli", "Ingredients: yogurt 3,2% m.f., fruits in variable ratios (raspberries, blueberries, red currant, black currant, strawberries, blackberries), musli, honey, chia seeds", 3.5, CategoryRepository.getAllCategories().get(6), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pizze/PIZZA SIR _1628 A.jpg"));
        products.add(new Product(78L, "Hummus salad", "Ingredients: hummus, cauliflower, cherry tomato, quinoa, cucumber, red cabbage, fennel, carrot, young green salad, sunflower oil, salt, black sesame, sesame", 3.5, CategoryRepository.getAllCategories().get(6), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pizze/PIZZA SUNKA SIR _1637.jpg"));
        // Packaged products
        products.add(new Product(79L, "Bread crumbs", "Ingredients: wheat flour type 550, water, yeast, salt, additives", 3.5, CategoryRepository.getAllCategories().get(7), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pakirani proizvodi/KRUSNE MRVICE 1853.jpg"));
        products.add(new Product(80L, "Poppy seed roll", "Ingredients: wheat flour type 550, poppy seeds, milk, sugar, eggs, sunflower oil, rum, apricot jam, butter, salt, vanilla sugar, spices", 3.5, CategoryRepository.getAllCategories().get(7), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pakirani proizvodi/makovnjaca.jpg"));
        products.add(new Product(81L, "Nut roll", "Ingredients: wheat flour type 550, walnuts, milk, sugar, eggs, rum, apricot jam, butter, salt, vanilla sugar, spices", 3.5, CategoryRepository.getAllCategories().get(7), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pakirani proizvodi/orehnjaca.jpg"));
        products.add(new Product(82L, "Viprodia bread", "Ingredients: whole grain wheat flour, wheat flour type 550, water, wheat bran, wheat gluten, soy flour, whole grain rye grits, yeast, salt, additives", 3.5, CategoryRepository.getAllCategories().get(7), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pakirani proizvodi/DIETETSKI KRUH  1860.jpg"));
        products.add(new Product(83L, "Domaći mlinci", "Ingredients: wheat flour type 550 and type 400, eggs, sunflower oil, lard, salt", 3.5, CategoryRepository.getAllCategories().get(7), "https://www.pekara-dubravica.hr/assets/uploads/Proizvodi/Pakirani proizvodi/Domaci_mlinci.jpg"));
    }

    public static List<Product> getAllProducts() {
        if (singleton == null) {
            singleton = new ProductRepository();
            return getAllProducts();
        }
        return singleton.products;
    }

    public static Optional<Product> getProductWithId(long productId) {
        return getAllProducts().stream().filter(p -> p.getId().equals(productId)).findFirst();
    }
}